import type { ClassLevel } from "@/types";

export interface CurriculumLesson {
  module: string;
  chapter: string;
  title: string;
  duration: number;
}

export const CURRICULUM: Record<ClassLevel, CurriculumLesson[]> = {
  "Form 1": [
    { module: "The World of Science", chapter: "Introduction to Science", title: "What is Science?", duration: 1 },
    { module: "The World of Science", chapter: "The Science Laboratory", title: "Laboratory equipment and safety rules", duration: 2 },
    { module: "The World of Science", chapter: "Measurement", title: "Measurement of length, mass and time", duration: 2 },
    { module: "The World of Science", chapter: "Measurement", title: "Units and measuring instruments", duration: 1 },
    { module: "Matter: Properties and Transformation", chapter: "States of Matter", title: "The three states of matter", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "States of Matter", title: "Changing states: melting, boiling, evaporation", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Properties of Materials", title: "Physical properties of matter", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Properties of Materials", title: "Density and floating", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Properties of Materials", title: "Simple experiments on density", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Forms of Energy", title: "Forms of energy and their uses", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Energy Sources", title: "Renewable and non-renewable energy sources", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Energy Transformation", title: "Energy transformations in everyday life", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Energy Transformation", title: "The energy chain in a torch and cooker", duration: 1 },
    { module: "Health Education", chapter: "Hygiene", title: "Personal hygiene and diseases", duration: 2 },
    { module: "Health Education", chapter: "Nutrition", title: "Balanced diet and food nutrients", duration: 2 },
    { module: "Environmental Education", chapter: "Pollution", title: "Types and effects of pollution", duration: 2 },
    { module: "Environmental Education", chapter: "Conservation", title: "Protecting our environment", duration: 1 },
    { module: "Technology", chapter: "Tools and Machines", title: "Simple tools and machines", duration: 2 },
    { module: "Technology", chapter: "Simple Machines", title: "Levers and their uses", duration: 1 },
    { module: "Technology", chapter: "Simple Machines", title: "Pulleys and inclined planes", duration: 1 },
    { module: "Technology", chapter: "Electricity", title: "Simple electric circuits", duration: 2 },
    { module: "Technology", chapter: "Electricity", title: "Conductors and insulators", duration: 2 },
    { module: "Technology", chapter: "Sound", title: "Producing and detecting sound", duration: 2 },
    { module: "Technology", chapter: "Light", title: "Sources and properties of light", duration: 2 },
    { module: "Technology", chapter: "Revision", title: "Revision and exercises", duration: 1 }
  ],
  "Form 2": [
    { module: "The World of Science", chapter: "Scientific Methods", title: "The scientific method and experiments", duration: 2 },
    { module: "The World of Science", chapter: "Measurement", title: "Measuring length, area and volume", duration: 2 },
    { module: "The World of Science", chapter: "Measurement", title: "Mass, volume and density of regular solids", duration: 2 },
    { module: "The World of Science", chapter: "Measurement", title: "Measuring time intervals", duration: 1 },
    { module: "Matter: Properties and Transformation", chapter: "States of Matter", title: "The particle model of matter", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Expansion", title: "Thermal expansion of solids and liquids", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Expansion", title: "Applications of expansion in daily life", duration: 1 },
    { module: "Matter: Properties and Transformation", chapter: "Pressure", title: "Pressure in solids and liquids", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Pressure", title: "Atmospheric pressure", duration: 2 },
    { module: "Matter: Properties and Transformation", chapter: "Elasticity", title: "Hooke's law and elastic materials", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Energy Sources", title: "Energy sources and conservation", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Work and Power", title: "Work, energy and power", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Work and Power", title: "Calculating power and efficiency", duration: 1 },
    { module: "Energy: Applications and Uses", chapter: "Heat Transfer", title: "Conduction, convection and radiation", duration: 2 },
    { module: "Energy: Applications and Uses", chapter: "Heat Transfer", title: "Applications of heat transfer", duration: 1 },
    { module: "Technology", chapter: "Electricity", title: "Static electricity and charges", duration: 2 },
    { module: "Technology", chapter: "Electricity", title: "Current and simple circuits", duration: 2 },
    { module: "Technology", chapter: "Magnetism", title: "Magnets and magnetic fields", duration: 2 },
    { module: "Technology", chapter: "Magnetism", title: "Making a magnet", duration: 1 },
    { module: "Technology", chapter: "Light", title: "Reflection of light and plane mirrors", duration: 2 },
    { module: "Technology", chapter: "Light", title: "Refraction of light", duration: 2 },
    { module: "Technology", chapter: "Sound", title: "Properties of sound waves", duration: 1 },
    { module: "Health Education", chapter: "The Body", title: "The senses and how they work", duration: 1 },
    { module: "Environmental Education", chapter: "Resources", title: "Sustainable use of resources", duration: 1 },
    { module: "Technology", chapter: "Revision", title: "Revision and exercises", duration: 1 }
  ],
  "Form 3": [
    { module: "Heat", chapter: "Temperature", title: "Temperature and thermometers", duration: 2 },
    { module: "Heat", chapter: "Temperature", title: "Types of thermometers and scales", duration: 2 },
    { module: "Heat", chapter: "Thermal Expansion", title: "Expansion of solids, liquids and gases", duration: 2 },
    { module: "Heat", chapter: "Thermal Expansion", title: "Applications of expansion", duration: 1 },
    { module: "Heat", chapter: "Heat Transfer", title: "Conduction, convection and radiation", duration: 2 },
    { module: "Heat", chapter: "Heat Transfer", title: "Applications and insulators", duration: 2 },
    { module: "Heat", chapter: "Heat Measurement", title: "Heat capacity and specific heat capacity", duration: 2 },
    { module: "Heat", chapter: "Change of State", title: "Latent heat and changes of state", duration: 2 },
    { module: "Heat", chapter: "Change of State", title: "Evaporation and boiling", duration: 1 },
    { module: "Heat", chapter: "Revision", title: "Revision and exercises", duration: 1 },
    { module: "Waves", chapter: "Introduction to Waves", title: "Types of waves: transverse and longitudinal", duration: 2 },
    { module: "Waves", chapter: "Properties of Waves", title: "Amplitude, wavelength, frequency and speed", duration: 2 },
    { module: "Waves", chapter: "Properties of Waves", title: "The wave equation and calculations", duration: 1 },
    { module: "Waves", chapter: "Sound Waves", title: "Production and propagation of sound", duration: 2 },
    { module: "Waves", chapter: "Sound Waves", title: "Reflection of sound and echo", duration: 1 },
    { module: "Electrical Energy", chapter: "Current Electricity", title: "Electric current and circuits", duration: 2 },
    { module: "Electrical Energy", chapter: "Current Electricity", title: "Ohm's law and resistance", duration: 2 },
    { module: "Electrical Energy", chapter: "Electrical Circuits", title: "Series and parallel circuits", duration: 2 },
    { module: "Electrical Energy", chapter: "Electrical Circuits", title: "Measuring current and voltage", duration: 2 },
    { module: "Electrical Energy", chapter: "Electrical Power", title: "Electrical power and energy", duration: 1 },
    { module: "Electrical Energy", chapter: "Electrical Power", title: "The electric bill and saving energy", duration: 1 },
    { module: "Electrical Energy", chapter: "Magnetism and Current", title: "Electromagnets and their uses", duration: 2 },
    { module: "Electrical Energy", chapter: "Magnetism and Current", title: "The electric bell and relay", duration: 1 },
    { module: "Projects", chapter: "Project Work", title: "Design and build a simple device", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Project presentation and report", duration: 2 }
  ],
  "Form 4": [
    { module: "Energy (Heat)", chapter: "Heat", title: "Temperature and heat: key differences", duration: 2 },
    { module: "Energy (Heat)", chapter: "Heat", title: "Measuring temperature", duration: 1 },
    { module: "Energy (Heat)", chapter: "Thermal Expansion", title: "Expansion of solids and its applications", duration: 2 },
    { module: "Energy (Heat)", chapter: "Thermal Expansion", title: "Expansion of liquids and gases", duration: 2 },
    { module: "Energy (Heat)", chapter: "Heat Transfer", title: "Conduction and convection", duration: 2 },
    { module: "Energy (Heat)", chapter: "Heat Transfer", title: "Radiation and vacuum flasks", duration: 2 },
    { module: "Energy (Heat)", chapter: "Heat Measurement", title: "Specific heat capacity and calculations", duration: 2 },
    { module: "Energy (Heat)", chapter: "Change of State", title: "Latent heat of fusion and vaporization", duration: 2 },
    { module: "Energy (Heat)", chapter: "Change of State", title: "Boiling, evaporation and factors", duration: 1 },
    { module: "Energy (Heat)", chapter: "Revision", title: "Revision and exercises", duration: 1 },
    { module: "Waves", chapter: "Wave Motion", title: "Describing wave motion", duration: 2 },
    { module: "Waves", chapter: "Wave Motion", title: "The wave equation and calculations", duration: 1 },
    { module: "Waves", chapter: "Sound Waves", title: "Sound in air: speed and echo", duration: 2 },
    { module: "Waves", chapter: "Light Waves", title: "Reflection: laws and plane mirrors", duration: 2 },
    { module: "Waves", chapter: "Light Waves", title: "Refraction and total internal reflection", duration: 2 },
    { module: "Electrical Energy", chapter: "Circuits", title: "Ohm's law and resistance", duration: 2 },
    { module: "Electrical Energy", chapter: "Circuits", title: "Series and parallel circuits", duration: 2 },
    { module: "Electrical Energy", chapter: "Electrical Energy", title: "Electrical power and energy calculations", duration: 2 },
    { module: "Electrical Energy", chapter: "Electrical Energy", title: "Cost of electricity", duration: 1 },
    { module: "Electrical Energy", chapter: "Magnetism", title: "Magnetic fields and field lines", duration: 2 },
    { module: "Electrical Energy", chapter: "Electromagnetism", title: "Electromagnets and applications", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Planning a practical project", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Building and testing", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Presenting results", duration: 1 },
    { module: "Energy (Heat)", chapter: "Revision", title: "Year revision and mock test", duration: 1 }
  ],
  "Form 5": [
    { module: "Mechanics", chapter: "Motion", title: "Distance, displacement, speed and velocity", duration: 2 },
    { module: "Mechanics", chapter: "Motion", title: "Acceleration and equations of motion", duration: 2 },
    { module: "Mechanics", chapter: "Motion", title: "Motion graphs", duration: 1 },
    { module: "Mechanics", chapter: "Forces", title: "Types of forces and their effects", duration: 2 },
    { module: "Mechanics", chapter: "Forces", title: "Newton's laws of motion", duration: 2 },
    { module: "Mechanics", chapter: "Forces", title: "Friction and applications", duration: 1 },
    { module: "Mechanics", chapter: "Work, Energy and Power", title: "Work, kinetic and potential energy", duration: 2 },
    { module: "Mechanics", chapter: "Work, Energy and Power", title: "Power and efficiency", duration: 1 },
    { module: "Mechanics", chapter: "Momentum", title: "Momentum and impulse", duration: 2 },
    { module: "Mechanics", chapter: "Revision", title: "Revision and exercises", duration: 1 },
    { module: "Fields (Magnetism and EM Induction)", chapter: "Magnetism", title: "Magnetic fields and flux", duration: 2 },
    { module: "Fields (Magnetism and EM Induction)", chapter: "Magnetism", title: "Magnetisation and magnetic materials", duration: 1 },
    { module: "Fields (Magnetism and EM Induction)", chapter: "Electromagnetic Induction", title: "Faraday's and Lenz's laws", duration: 2 },
    { module: "Fields (Magnetism and EM Induction)", chapter: "Electromagnetic Induction", title: "Generators and transformers", duration: 2 },
    { module: "Fields (Magnetism and EM Induction)", chapter: "Electromagnetic Induction", title: "Transmission of electricity", duration: 1 },
    { module: "Modern Physics", chapter: "Atomic Structure", title: "Rutherford's model and isotopes", duration: 2 },
    { module: "Modern Physics", chapter: "Radioactivity", title: "Types of radiation and half-life", duration: 2 },
    { module: "Modern Physics", chapter: "Radioactivity", title: "Uses and dangers of radiation", duration: 1 },
    { module: "Modern Physics", chapter: "The Nucleus", title: "Nuclear fission and fusion", duration: 2 },
    { module: "Modern Physics", chapter: "The Nucleus", title: "Applications of nuclear energy", duration: 1 },
    { module: "Mechanics", chapter: "Circular Motion", title: "Angular motion and centripetal force", duration: 2 },
    { module: "Mechanics", chapter: "Gravitation", title: "Gravitational field and weight", duration: 2 },
    { module: "Mechanics", chapter: "Fluid Mechanics", title: "Pressure in fluids and upthrust", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Research and design project", duration: 2 },
    { module: "Projects", chapter: "Project Work", title: "Report and presentation", duration: 1 }
  ],
  "Lower Sixth": [
    { module: "Mechanics", chapter: "Kinematics", title: "Scalars, vectors and measurement errors", duration: 2 },
    { module: "Mechanics", chapter: "Kinematics", title: "Equations of uniformly accelerated motion", duration: 2 },
    { module: "Mechanics", chapter: "Kinematics", title: "Projectile motion", duration: 2 },
    { module: "Mechanics", chapter: "Dynamics", title: "Newton's laws of motion", duration: 2 },
    { module: "Mechanics", chapter: "Dynamics", title: "Momentum and collisions", duration: 2 },
    { module: "Mechanics", chapter: "Dynamics", title: "Friction and resistive forces", duration: 2 },
    { module: "Mechanics", chapter: "Energy", title: "Work, energy and power", duration: 2 },
    { module: "Mechanics", chapter: "Energy", title: "Conservation of energy", duration: 1 },
    { module: "Mechanics", chapter: "Circular Motion", title: "Uniform circular motion", duration: 2 },
    { module: "Mechanics", chapter: "Revision", title: "Revision and exercises", duration: 1 },
    { module: "Thermal Physics", chapter: "Temperature", title: "Thermal equilibrium and thermometers", duration: 2 },
    { module: "Thermal Physics", chapter: "Thermal Expansion", title: "Expansion of solids, liquids and gases", duration: 2 },
    { module: "Thermal Physics", chapter: "Heat Transfer", title: "Conduction, convection and radiation", duration: 2 },
    { module: "Thermal Physics", chapter: "Heat Capacity", title: "Specific and molar heat capacities", duration: 2 },
    { module: "Thermal Physics", chapter: "Change of State", title: "Latent heat and phase changes", duration: 2 },
    { module: "Waves", chapter: "Wave Motion", title: "Progressive waves and the wave equation", duration: 2 },
    { module: "Waves", chapter: "Wave Motion", title: "Stationary waves", duration: 2 },
    { module: "Waves", chapter: "Sound", title: "Sound waves and the Doppler effect", duration: 2 },
    { module: "Waves", chapter: "Optics", title: "Reflection and plane mirrors", duration: 1 },
    { module: "Waves", chapter: "Optics", title: "Refraction and Snell's law", duration: 2 },
    { module: "Waves", chapter: "Optics", title: "Lenses and the lens equation", duration: 2 },
    { module: "Waves", chapter: "Optics", title: "Optical instruments", duration: 1 },
    { module: "Waves", chapter: "Interference", title: "Interference and diffraction of light", duration: 2 },
    { module: "Thermal Physics", chapter: "Gas Laws", title: "Ideal gas laws", duration: 2 },
    { module: "Thermal Physics", chapter: "Gas Laws", title: "Kinetic theory of gases", duration: 2 }
  ],
  "Upper Sixth": [
    { module: "Electricity and Magnetism", chapter: "Electrostatics", title: "Coulomb's law and electric fields", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Electrostatics", title: "Electric potential and capacitance", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Current Electricity", title: "Current, resistance and Ohm's law", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Current Electricity", title: "Resistivity and temperature effects", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Circuits", title: "Kirchhoff's laws", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Circuits", title: "RC circuits and time constants", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Magnetic Fields", title: "Force on a current-carrying conductor", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Magnetic Fields", title: "Force on a moving charge", duration: 1 },
    { module: "Electricity and Magnetism", chapter: "Electromagnetic Induction", title: "Faraday's law and Lenz's law", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Electromagnetic Induction", title: "AC generators and transformers", duration: 2 },
    { module: "Modern Physics", chapter: "Atomic Physics", title: "Bohr model and energy levels", duration: 2 },
    { module: "Modern Physics", chapter: "Atomic Physics", title: "X-rays and their production", duration: 2 },
    { module: "Modern Physics", chapter: "Quantum Physics", title: "The photoelectric effect", duration: 2 },
    { module: "Modern Physics", chapter: "Quantum Physics", title: "Wave-particle duality", duration: 1 },
    { module: "Modern Physics", chapter: "Nuclear Physics", title: "Radioactive decay and half-life", duration: 2 },
    { module: "Modern Physics", chapter: "Nuclear Physics", title: "Fission, fusion and reactors", duration: 2 },
    { module: "Practical Physics", chapter: "Measurement", title: "Errors, precision and significant figures", duration: 2 },
    { module: "Practical Physics", chapter: "Experiments", title: "Designing experiments and plotting graphs", duration: 2 },
    { module: "Practical Physics", chapter: "Experiments", title: "Electrical experiments", duration: 2 },
    { module: "Practical Physics", chapter: "Experiments", title: "Mechanical and thermal experiments", duration: 1 },
    { module: "Electricity and Magnetism", chapter: "Alternating Current", title: "AC circuits and RMS values", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Alternating Current", title: "Reactance and resonance", duration: 2 },
    { module: "Electricity and Magnetism", chapter: "Electronics", title: "Semiconductors and diodes", duration: 1 },
    { module: "Modern Physics", chapter: "Applications", title: "Applications of modern physics", duration: 1 },
    { module: "Practical Physics", chapter: "Revision", title: "Revision and mock examination", duration: 1 }
  ]
};

export const PHYSICS_PERIODS_PER_WEEK: Partial<Record<ClassLevel, number>> = {
  "Form 1": 2,
  "Form 2": 2,
  "Form 3": 3,
  "Form 4": 3,
  "Form 5": 4,
  "Lower Sixth": 5,
  "Upper Sixth": 5
};

export const CLASS_MODULES: Record<ClassLevel, string[]> = {
  "Form 1": ["The World of Science", "Matter: Properties and Transformation", "Energy: Applications and Uses", "Health Education", "Environmental Education", "Technology"],
  "Form 2": ["The World of Science", "Matter: Properties and Transformation", "Energy: Applications and Uses", "Technology", "Health Education", "Environmental Education"],
  "Form 3": ["Heat", "Waves", "Electrical Energy", "Projects"],
  "Form 4": ["Energy (Heat)", "Waves", "Electrical Energy", "Projects"],
  "Form 5": ["Mechanics", "Fields (Magnetism and EM Induction)", "Modern Physics", "Projects"],
  "Lower Sixth": ["Mechanics", "Thermal Physics", "Waves and Optics"],
  "Upper Sixth": ["Electricity and Magnetism", "Modern Physics", "Practical Physics"]
};
